apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: myapp-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(dashy.itdynatsy.eu) && PathPrefix(/)
      kind: Rule
      services:
        - name: my-app-service
          port: 80
