name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t bwoodyr/k8s_test:latest .
          docker push bwoodyr/k8s_test:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 1. Nastavenie Kubernetes prístupu
      - name: Set up Kubernetes access
        run: |
          kubectl config set-cluster my-cluster --server=${{ secrets.KUBE_API_URL }}
          kubectl config set-credentials user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context my-context --cluster=my-cluster --user=user
          kubectl config use-context my-context

      # 2. Nasadenie do Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f manifests/

      # 3. Overenie, že pody sú nasadené
      - name: Verify Deployment
        run: |
          kubectl get pods
